name: Lighthouse
on:
  push:
 #   branches: [main, github-actions-cypress-tests ]
  pull_request:
#    branches: [main]
jobs:
  Lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: npm install, build
        run: |
          npm install
          ESLINT_NO_DEV_ERRORS=true npm run build
      - name: Check Chrome version
        run: google-chrome-stable --version
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun --upload.target=temporary-public-storage
      - name: Save lighthouse reports
        run: |
          mkdir -p public/a11y_reports/lighthouse
          cp -r .lighthouseci/* public/a11y_reports/lighthouse
      - name: Archive lighthouse accessibility report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse accessibility report 
          path: public/a11y_reports/lighthouse
#      - name: Fail if accessibility issues were found
#        run: grep -q "\"score\":1" public/a11y_reports/lighthouse/lhr-*.report.html || exit 1