name: pa11y
on:
  push:
    branches: [main, github-actions-cypress-tests ]
jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - run: npm install
      - name: Build
        run: npm run build --if-present
      - name: Start server if not running then run pa11y
        run: |
          if ! curl -s http://localhost:3000 > /dev/null; then
            npm start &
            npx wait-on http://localhost:3000
          fi
          mkdir -p public/a11y_reports
          npm install -g pa11y pa11y-reporter-html
          pa11y http://localhost:3000 --reporter html > public/a11y_reports/pally_a11y_report.html
      - name: Archive pally accessibility report as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: pally accessibility report 
          path: public/a11y_reports/pally_a11y_report.html
      - name: Fail if accessibility issues were found
        run: grep -q "0 Errors" public/a11y_reports/pally_a11y_report.html || exit 1